"""initial schema

Revision ID: 509505219ab5
Revises: 
Create Date: 2025-09-16 01:04:02.599908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509505219ab5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumo',
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=False),
    sa.Column('stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.CheckConstraint('stock >= 0', name='insumo_stock_chk'),
    sa.PrimaryKeyConstraint('insumo_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ubicacion',
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('comuna', sa.String(length=50), nullable=False),
    sa.Column('nombre_sector', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('ubicacion_id')
    )
    op.create_table('usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=50), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("rol IN ('admin','veterinario','asistente')", name='usuario_rol_chk'),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('correo', name='usuario_correo_uk')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('ix_usuario_correo', ['correo'], unique=False)

    op.create_table('animal',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('codigo_qr', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("sexo IN ('Macho','Hembra') OR sexo IS NULL", name='animal_sexo_chk'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicacion.ubicacion_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('animal_id'),
    sa.UniqueConstraint('codigo_qr'),
    sa.UniqueConstraint('codigo_qr', name='animal_codigo_qr_uk')
    )
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.create_index('ix_animal_ubicacion', ['ubicacion_id'], unique=False)

    op.create_table('foto_animal',
    sa.Column('foto_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('foto_id')
    )
    with op.batch_alter_table('foto_animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foto_animal_animal_id'), ['animal_id'], unique=False)

    op.create_table('historial_estado',
    sa.Column('historial_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_estado', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('proximo_control', sa.Date(), nullable=True),
    sa.CheckConstraint("estado in ('En tratamiento','Recuperado','Adoptado','Fallecido','Observacion')", name='historial_estado_chk'),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('historial_id')
    )
    with op.batch_alter_table('historial_estado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_estado_animal_id'), ['animal_id'], unique=False)

    op.create_table('tratamiento',
    sa.Column('tratamiento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('fecha_tratamiento', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("estado IN ('Pendiente','Aprobado','Rechazado')", name='tratamiento_estado_chk'),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tratamiento_id')
    )
    with op.batch_alter_table('tratamiento', schema=None) as batch_op:
        batch_op.create_index('ix_tratamiento_animal_fecha', ['animal_id', 'fecha_tratamiento'], unique=False)

    op.create_table('tratamiento_insumo',
    sa.Column('tratamiento_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='tratamiento_insumo_cantidad_chk'),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.insumo_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tratamiento_id'], ['tratamiento.tratamiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tratamiento_id', 'insumo_id')
    )
    with op.batch_alter_table('tratamiento_insumo', schema=None) as batch_op:
        batch_op.create_index('ix_tratinsumo_insumo', ['insumo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tratamiento_insumo', schema=None) as batch_op:
        batch_op.drop_index('ix_tratinsumo_insumo')

    op.drop_table('tratamiento_insumo')
    with op.batch_alter_table('tratamiento', schema=None) as batch_op:
        batch_op.drop_index('ix_tratamiento_animal_fecha')

    op.drop_table('tratamiento')
    with op.batch_alter_table('historial_estado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_estado_animal_id'))

    op.drop_table('historial_estado')
    with op.batch_alter_table('foto_animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foto_animal_animal_id'))

    op.drop_table('foto_animal')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_index('ix_animal_ubicacion')

    op.drop_table('animal')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('ix_usuario_correo')

    op.drop_table('usuario')
    op.drop_table('ubicacion')
    op.drop_table('insumo')
    # ### end Alembic commands ###
