"""init animal

Revision ID: 85149d0aac4b
Revises: 
Create Date: 2025-09-06 12:35:48.367504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85149d0aac4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('especie', sa.String(length=50), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('codigo_qr', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('animal_id'),
    sa.UniqueConstraint('codigo_qr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    # ### end Alembic commands ###
