"""add proximo_control to historial_estado

Revision ID: a0b257291e55
Revises: 912e48b9e4b8
Create Date: 2025-09-13 02:19:13.818347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b257291e55'
down_revision = '912e48b9e4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_estado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proximo_control', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_estado', schema=None) as batch_op:
        batch_op.drop_column('proximo_control')

    # ### end Alembic commands ###
