"""modelo completo

Revision ID: e939ee9dadd8
Revises: 85149d0aac4b
Create Date: 2025-09-06 14:57:42.621526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e939ee9dadd8'
down_revision = '85149d0aac4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumo',
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.CheckConstraint('stock >= 0', name='insumo_stock_chk'),
    sa.PrimaryKeyConstraint('insumo_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ubicacion',
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('comuna', sa.String(length=50), nullable=False),
    sa.Column('nombre_sector', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('ubicacion_id')
    )
    op.create_table('usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=50), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint("rol IN ('veterinario','asistente')", name='usuario_rol_chk'),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('fotoanimal',
    sa.Column('foto_id', sa.Integer(), nullable=False),
    sa.Column('url_foto', sa.String(length=500), nullable=False),
    sa.Column('fecha_foto', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('foto_id')
    )
    op.create_table('historialestado',
    sa.Column('historialestado_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('fecha_estado', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('historialestado_id')
    )
    with op.batch_alter_table('historialestado', schema=None) as batch_op:
        batch_op.create_index('ix_historialestado_animal_fecha', ['animal_id', 'fecha_estado'], unique=False)

    op.create_table('tratamiento',
    sa.Column('tratamiento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('fecha_tratamiento', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("estado IN ('Pendiente','Aprobado','Rechazado')", name='tratamiento_estado_chk'),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tratamiento_id')
    )
    with op.batch_alter_table('tratamiento', schema=None) as batch_op:
        batch_op.create_index('ix_tratamiento_animal_fecha', ['animal_id', 'fecha_tratamiento'], unique=False)

    op.create_table('tratamiento_insumo',
    sa.Column('tratamiento_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='tratamiento_insumo_cantidad_chk'),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.insumo_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tratamiento_id'], ['tratamiento.tratamiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tratamiento_id', 'insumo_id')
    )
    with op.batch_alter_table('tratamiento_insumo', schema=None) as batch_op:
        batch_op.create_index('ix_tratinsumo_insumo', ['insumo_id'], unique=False)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ubicacion_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('animal_codigo_qr_uk', ['codigo_qr'])
        batch_op.create_index('ix_animal_ubicacion', ['ubicacion_id'], unique=False)
        batch_op.create_foreign_key(None, 'ubicacion', ['ubicacion_id'], ['ubicacion_id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['usuario_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_animal_ubicacion')
        batch_op.drop_constraint('animal_codigo_qr_uk', type_='unique')
        batch_op.drop_column('ubicacion_id')
        batch_op.drop_column('usuario_id')

    with op.batch_alter_table('tratamiento_insumo', schema=None) as batch_op:
        batch_op.drop_index('ix_tratinsumo_insumo')

    op.drop_table('tratamiento_insumo')
    with op.batch_alter_table('tratamiento', schema=None) as batch_op:
        batch_op.drop_index('ix_tratamiento_animal_fecha')

    op.drop_table('tratamiento')
    with op.batch_alter_table('historialestado', schema=None) as batch_op:
        batch_op.drop_index('ix_historialestado_animal_fecha')

    op.drop_table('historialestado')
    op.drop_table('fotoanimal')
    op.drop_table('usuario')
    op.drop_table('ubicacion')
    op.drop_table('insumo')
    # ### end Alembic commands ###
