"""usuario con login

Revision ID: e94e81936b4c
Revises: e939ee9dadd8
Create Date: 2025-09-06 20:52:47.926489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94e81936b4c'
down_revision = 'e939ee9dadd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))
        batch_op.create_index('ix_usuario_correo', ['correo'], unique=False)
        batch_op.create_unique_constraint('usuario_correo_uk', ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint('usuario_correo_uk', type_='unique')
        batch_op.drop_index('ix_usuario_correo')
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
