"""historial estado + foto animal

Revision ID: f925d09c0800
Revises: fc7cd92fd4db
Create Date: 2025-09-07 23:21:43.926063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f925d09c0800'
down_revision = 'fc7cd92fd4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foto_animal',
    sa.Column('foto_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('foto_id')
    )
    with op.batch_alter_table('foto_animal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foto_animal_animal_id'), ['animal_id'], unique=False)

    op.create_table('historial_estado',
    sa.Column('historial_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_estado', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("estado in ('En tratamiento','Recuperado','Adoptado','Fallecido','Observación')", name='historial_estado_chk'),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('historial_id')
    )
    with op.batch_alter_table('historial_estado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_estado_animal_id'), ['animal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_estado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_estado_animal_id'))

    op.drop_table('historial_estado')
    with op.batch_alter_table('foto_animal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foto_animal_animal_id'))

    op.drop_table('foto_animal')
    # ### end Alembic commands ###
